<a href="https://colab.research.google.com/github/thedeveshpareek/ML-Training-assignment/blob/main/Goeduhub_Assignment15.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Build a spam filter using Python and the multinomial Naive Bayes algorithm.** 

**Check Spam or Ham? Email Classifier Using Python using MultinomialNB.**

#devesh pareek
# go_stp_8589

## Import Libraries

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline
import seaborn as sb
import sklearn
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import confusion_matrix, accuracy_score

## Load Dataset

In [ ]:
spam = pd.read_csv("/content/drive/MyDrive/Goeduhub/spam.csv")
spam.head()

Category                                            Message
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...

## Checking null values & applying label encoding for cateogrical variable

In [ ]:
spam.isnull().sum()

Category    0
Message     0
dtype: int64

In [ ]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()
spam["Category"] = le.fit_transform(spam["Category"])
spam["Category"]

0       0
1       0
2       1
3       0
4       0
       ..
5567    1
5568    0
5569    0
5570    0
5571    0
Name: Category, Length: 5572, dtype: int64

## Feature & Target

In [ ]:
feature = spam["Message"]
target = spam["Category"]

## Text Processing

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer, TfidfTransformer

In [ ]:
# covert textual data into numeric form

count_vect = CountVectorizer()
xtrain = count_vect.fit_transform(feature)
print(xtrain.toarray()) 
print(xtrain.shape)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
(5572, 8709)


In [ ]:
tfidf_transformer = TfidfTransformer()
xtrain_tfidf = tfidf_transformer.fit_transform(xtrain)
print(xtrain_tfidf.shape)

(5572, 8709)


## Divide data into training and testing

In [ ]:
xtrain, xtest, ytrain, ytest = train_test_split(xtrain_tfidf, target, test_size = 0.3, random_state = 42)
print("Shape of xtrain:", xtrain.shape)
print("Shape of xtest:", xtest.shape)
print("Shape of ytrain:", ytrain.shape)
print("Shape of ytest:",ytest.shape)

Shape of xtrain: (3900, 8709)
Shape of xtest: (1672, 8709)
Shape of ytrain: (3900,)
Shape of ytest: (1672,)


## Create a model and fit training data

In [ ]:
mnb = MultinomialNB()
mnb.fit(xtrain, ytrain)

MultinomialNB(alpha=1.0, class_prior=None, fit_prior=True)

## Predcitions

In [ ]:
ypred = mnb.predict(xtest)
print("Prediction made by model:\n", ypred)

Prediction made by model:
 [0 0 0 ... 0 1 0]


## Confusion Matrix and Accuracy score

In [ ]:
matrix = confusion_matrix(ytest, ypred)
print("Confusion Matrix:\n", matrix)

Confusion Matrix:
 [[1448    0]
 [  66  158]]


In [ ]:
accuracy = accuracy_score(ytest, ypred)
print("Accuracy: {}%".format(accuracy*100))

Accuracy: 96.05263157894737%
